# Generated by Django 3.0.5 on 2020-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('mypassword', models.CharField(max_length=50)),
            ],
        ),
    ]
