# Generated by Django 3.0.5 on 2020-05-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='myname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='mypassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='uname',
            new_name='username',
        ),
    ]
