# Generated by Django 3.0.5 on 2020-05-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200526_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userbase',
        ),
    ]
